# -*- coding: utf-8 -*-
"""yapayzeka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17VVj_CCV0vHrQB7D33l462LnwFMUnXRH
"""

7# =========================
# HAFTA 1
# Import libraries
# =========================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from imblearn.over_sampling import SMOTE

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (8, 5)

# =========================
# Load dataset
# =========================
df = pd.read_csv("malnutrition_data .csv")
df.head()

# =========================
# Dataset overview
# =========================
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

# =========================
# Standardisasi kolom teks
# =========================
df['nutrition_status'] = df['nutrition_status'].str.lower().str.strip()

# =========================
# Cek nilai tidak valid
# =========================
invalid_data = df[
    (df['age_months'] < 0) |
    (df['weight_kg'] <= 0) |
    (df['height_cm'] <= 0) |
    (df['muac_cm'] <= 0) |
    (df['bmi'] <= 0)
]

print("Jumlah data tidak valid:", invalid_data.shape[0])
invalid_data.head()

# =========================
# Hapus nilai tidak valid
# =========================
df = df[
    (df['age_months'] >= 0) &
    (df['weight_kg'] > 0) &
    (df['height_cm'] > 0) &
    (df['muac_cm'] > 0) &
    (df['bmi'] > 0)
]

# =========================
# Ubah tipe data kategori
# =========================
df['nutrition_status'] = df['nutrition_status'].astype('category')

# =========================
# Reset index setelah cleaning
# =========================
df = df.reset_index(drop=True)

print("Final shape after cleaning:", df.shape)

# =========================
# Drop duplicates if any
# =========================
df = df.drop_duplicates()
print("New shape after removing duplicates:", df.shape)

# =========================
# Basic statistical summary
# =========================
df.describe()

# =========================
# Check target distribution
# =========================
print(df["nutrition_status"].value_counts())
print("\nPercentage:")
print(df["nutrition_status"].value_counts(normalize=True) * 100)

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x="nutrition_status", data=df)
plt.title("Nutrition Status Distribution")
plt.xlabel("Nutrition Status")
plt.ylabel("Count")
plt.show()

"""# **HAFTA 3**"""

# =========================
# HAFTA 3
# Feature analysis
# =========================
numeric_cols = ["age_months", "weight_kg", "height_cm", "muac_cm", "bmi"]

for col in numeric_cols:
    plt.figure()
    sns.histplot(df[col], bins=30, kde=True)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.show()

# Boxplot per feature by class
for col in numeric_cols:
    plt.figure(figsize=(8, 5))
    sns.boxplot(data=df, x="nutrition_status", y=col)
    plt.title(f"{col} by nutrition_status")
    plt.show()

"""Ini buat lihat perbedaan tiap kelas

Contoh:

MUAC keliatan beda banget antara normal vs severe
BMI hampir sama semua → kurang penting

👉 Kesimpulan:
MUAC = fitur paling kuat
"""

# Mean values by nutrition class
df.groupby("nutrition_status")[numeric_cols].mean()

# Correlation heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

"""Ini nunjukin hubungan antar fitur

warna terang = hubungan kuat
warna gelap = lemah

Contoh:

age, height, weight saling berkaitan
MUAC agak beda sendiri → bagus buat model

👉 Artinya:
MUAC punya info unik → penting banget
"""

# =========================
# Min-Max normalization graphs (0-1)
# =========================
minmax_scaler = MinMaxScaler()
scaled_data = pd.DataFrame(minmax_scaler.fit_transform(df[numeric_cols]), columns=numeric_cols)

colors = ["blue", "green", "red", "purple", "orange"]

plt.figure(figsize=(20, 5))
for i, col in enumerate(numeric_cols, 1):
    plt.subplot(1, 5, i)
    sns.histplot(scaled_data[col], bins=30, kde=True, color=colors[i-1])
    plt.title(f"Ölçeklenmiş {col} (0-1)")
    plt.xlabel(f"{col} (Scaled)")
    plt.ylabel("Count")

plt.suptitle("3. Hafta: Normalizasyon Grafikleri", fontsize=18, y=1.05)
plt.tight_layout()
plt.show()

"""Ini setelah data di-scale jadi 0–1

👉 Tujuannya:
biar semua fitur “adil” di model

Kalau nggak:

weight bisa dominan
fitur lain kalah

# **Hafta 4: Encoding, preprocessing, train-test split**
"""

# =========================
# Encode target
# normal / moderate / severe -> numeric
# =========================
label_encoder = LabelEncoder()
df["nutrition_status_encoded"] = label_encoder.fit_transform(df["nutrition_status"])

print("Class mapping:")
for i, cls in enumerate(label_encoder.classes_):
    print(f"{cls} -> {i}")

"""Di dataset kan labelnya masih:

normal
moderate
severe

Nah model ML itu gak ngerti tulisan, jadi harus diubah jadi angka.

Hasilnya:

0 = moderate
1 = normal
2 = severe
"""

# Features and target
X = df[numeric_cols]
y = df["nutrition_status_encoded"]

"""Penjelasan:
X = input (umur, berat, tinggi, MUAC, BMI)
y = output (status gizi)

👉 gampangnya:

X = data anak
y = hasil diagnosis
"""

# Train-test split
# stratify=y penting supaya distribusi kelas tetap proporsional
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train distribution:\n", y_train.value_counts())
print("y_test distribution:\n", y_test.value_counts())

"""Hafta 4: System architecture draft secara coding

Urutan pipeline kita:

Data → Cleaning → EDA → Encoding → Split → SMOTE → Scaling → Model → Tuning → Evaluation

# **Hafta 5: Model geliştirme (Logistic Regression ve Random Forest)**

5A. SMOTE pada training set
"""

# =========================
# Apply SMOTE only on training data
# =========================
smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(pd.Series(y_train_smote).value_counts())

"""5B. Standardization

Untuk Logistic Regression, scaling penting.
Untuk Random Forest, scaling sebenarnya tidak wajib, tapi kita tetap bikin rapi.
"""

# =========================
# Standard scaling
# =========================
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_smote)
X_test_scaled = scaler.transform(X_test)

"""Logistic Regression baseline

"""

# =========================
# Logistic Regression baseline
# =========================
log_reg = LogisticRegression(max_iter=2000, random_state=42)
log_reg.fit(X_train_scaled, y_train_smote)

y_pred_log = log_reg.predict(X_test_scaled)

print("=== Logistic Regression ===")
print("Accuracy:", accuracy_score(y_test, y_pred_log))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_log, target_names=label_encoder.classes_))

cm_log = confusion_matrix(y_test, y_pred_log)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_log, display_labels=label_encoder.classes_)
disp.plot(cmap="Blues")
plt.title("Confusion Matrix - Logistic Regression")
plt.show()

"""5D. Random Forest baseline"""

# =========================
# Random Forest baseline
# =========================
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_smote, y_train_smote)

y_pred_rf = rf.predict(X_test)

print("=== Random Forest ===")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf, target_names=label_encoder.classes_))

cm_rf = confusion_matrix(y_test, y_pred_rf)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_rf, display_labels=label_encoder.classes_)
disp.plot(cmap="Greens")
plt.title("Confusion Matrix - Random Forest")
plt.show()

"""# **6) Hafta 6: Model optimization + hyperparameter tuning**

6A. Logistic Regression tuning
"""

# =========================
# Logistic Regression tuning
# =========================
param_grid_log = {
    "C": [0.01, 0.1, 1, 10, 100],
    "solver": ["lbfgs", "liblinear"],
    "class_weight": [None, "balanced"]
}

grid_log = GridSearchCV(
    LogisticRegression(max_iter=3000, random_state=42),
    param_grid=param_grid_log,
    cv=5,
    scoring="f1_weighted",
    n_jobs=-1
)

grid_log.fit(X_train_scaled, y_train_smote)

print("Best Logistic Regression Params:", grid_log.best_params_)
print("Best CV Score:", grid_log.best_score_)

best_log = grid_log.best_estimator_
y_pred_best_log = best_log.predict(X_test_scaled)

print("=== Tuned Logistic Regression ===")
print("Accuracy:", accuracy_score(y_test, y_pred_best_log))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_log, target_names=label_encoder.classes_))

cm_best_log = confusion_matrix(y_test, y_pred_best_log)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_best_log, display_labels=label_encoder.classes_)
disp.plot(cmap="Purples")
plt.title("Confusion Matrix - Tuned Logistic Regression")
plt.show()

"""6B. Random Forest tuning"""

# =========================
# Random Forest tuning
# =========================
param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier

random_rf = RandomizedSearchCV(
    RandomForestClassifier(
        random_state=42,
        class_weight="balanced"
    ),
    param_distributions=param_grid_rf,
    n_iter=10,
    cv=3,
    scoring="f1_weighted",
    n_jobs=-1,
    random_state=42
)

random_rf.fit(X_train_smote, y_train_smote)

best_rf = random_rf.best_estimator_
y_pred_best_rf = best_rf.predict(X_test)

print("=== Tuned Random Forest ===")
print("Accuracy:", accuracy_score(y_test, y_pred_best_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_best_rf, target_names=label_encoder.classes_))

cm_best_rf = confusion_matrix(y_test, y_pred_best_rf)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_best_rf, display_labels=label_encoder.classes_)
disp.plot(cmap="Greens")
plt.title("Confusion Matrix - Tuned Random Forest")
plt.show()

from sklearn.tree import plot_tree

plt.figure(figsize=(20,10))
plot_tree(
    best_rf.estimators_[0],
    feature_names=numeric_cols,
    class_names=label_encoder.classes_,
    filled=True,
    max_depth=3
)
plt.title("Decision Tree (Simplified - Top Levels)")
plt.show()

"""# **7) Hafta 7: Test ve performans değerlendirmesi**

7A. Bandingkan semua model
"""

from sklearn.metrics import accuracy_score, f1_score

results = []

# Logistic Regression
results.append({
    "model": "Logistic Regression",
    "accuracy": accuracy_score(y_test, y_pred_log),
    "f1": f1_score(y_test, y_pred_log, average='weighted')
})

# Random Forest
results.append({
    "model": "Random Forest",
    "accuracy": accuracy_score(y_test, y_pred_rf),
    "f1": f1_score(y_test, y_pred_rf, average='weighted')
})

import pandas as pd

results_df = pd.DataFrame(results)
print(results_df)

print("Best Params:", random_rf.best_params_)
print("Best CV Score:", random_rf.best_score_)

best_model_row = results_df.loc[results_df['f1'].idxmax()]

print("\n=== FINAL BEST MODEL ===")
print(best_model_row)

"""7B. Feature importance dari Random Forest"""

# =========================
# Feature importance
# =========================
importances = best_rf.feature_importances_
feature_importance_df = pd.DataFrame({
    "Feature": numeric_cols,
    "Importance": importances
}).sort_values(by="Importance", ascending=False)

feature_importance_df

plt.figure(figsize=(8, 5))
sns.barplot(data=feature_importance_df, x="Importance", y="Feature")
plt.title("Feature Importance - Tuned Random Forest")
plt.show()

"""7C. Prediksi data baru"""

# =========================
# Predict new sample
# urutan fitur:
# age_months, weight_kg, height_cm, muac_cm, bmi
# =========================
new_data = pd.DataFrame([{
    "age_months": 24,
    "weight_kg": 5,
    "height_cm": 70,
    "muac_cm": 10,
    "bmi": 10
}])

# Logistic Regression pakai scaler
new_data_scaled = scaler.transform(new_data)
pred_log = best_log.predict(new_data_scaled)
pred_rf = best_rf.predict(new_data)

print("Tuned Logistic Regression Prediction:", label_encoder.inverse_transform(pred_log)[0])
print("Tuned Random Forest Prediction:", label_encoder.inverse_transform(pred_rf)[0])

print(best_log.predict_proba(new_data_scaled))
print(best_rf.predict_proba(new_data))

df.groupby("nutrition_status")[numeric_cols].agg(["min", "max", "mean"])

new_data = pd.DataFrame([{
    "age_months": 24,
    "weight_kg": 7.2,
    "height_cm": 75,
    "muac_cm": 12.2,
    "bmi": 12.8
}])

new_data = new_data[numeric_cols]

pred = best_rf.predict(new_data)
result = label_encoder.inverse_transform(pred)

proba = best_rf.predict_proba(new_data)

print("Predicted:", result[0])
for cls, p in zip(label_encoder.classes_, proba[0]):
    print(f"{cls}: {p:.2%}")

new_data = pd.DataFrame([{
    "age_months": 24,
    "weight_kg": 5.8,
    "height_cm": 70,
    "muac_cm": 11.0,
    "bmi": 11.5
}])

new_data = new_data[numeric_cols]

pred = best_rf.predict(new_data)
result = label_encoder.inverse_transform(pred)

proba = best_rf.predict_proba(new_data)

print("Predicted:", result[0])
for cls, p in zip(label_encoder.classes_, proba[0]):
    print(f"{cls}: {p:.2%}")

new_data = pd.DataFrame([{
    "age_months": 36,
    "weight_kg": 3,
    "height_cm": 60,
    "muac_cm": 10.0,
    "bmi": 11.5
}])

new_data = new_data[numeric_cols]

pred = best_rf.predict(new_data)
result = label_encoder.inverse_transform(pred)

proba = best_rf.predict_proba(new_data)

print("Predicted:", result[0])
for cls, p in zip(label_encoder.classes_, proba[0]):
    print(f"{cls}: {p:.2%}")

"""Di hafta 7 kita menemukan best model predictionnya = random forest tapi di hafta 8 kita kana mengupdatenya lagi pake 2 model baru XGboost sama Catboost

# **Hafta 8**

Disini kita update best model random forest dengan bandingin model yang baru
"""


from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

xgb_model = XGBClassifier(
    objective="multi:softprob",
    num_class=3,
    random_state=42,
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8
)

xgb_model.fit(X_train_smote, y_train_smote)

y_pred_xgb = xgb_model.predict(X_test)

print("=== XGBoost ===")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb, target_names=label_encoder.classes_))
xgb_model.save_model("xgboost_model.json")

xgb_model.save_model("xgboost_model.json")

cm_xgb = confusion_matrix(y_test, y_pred_xgb)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_xgb, display_labels=label_encoder.classes_)
disp.plot(cmap="Oranges")
plt.title("Confusion Matrix - XGBoost")
plt.show()


from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, f1_score

cat_model = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.1,
    loss_function='MultiClass',
    eval_metric='Accuracy',
    random_state=42,
    verbose=0
)

cat_model.fit(X_train_smote, y_train_smote)

y_pred_cat = cat_model.predict(X_test)
y_pred_cat = y_pred_cat.flatten().astype(int)

print("=== CatBoost ===")
print("Accuracy:", accuracy_score(y_test, y_pred_cat))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_cat, target_names=label_encoder.classes_))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm_cat = confusion_matrix(y_test, y_pred_cat)
disp = ConfusionMatrixDisplay(confusion_matrix=cm_cat, display_labels=label_encoder.classes_)
disp.plot(cmap="Purples")
plt.title("Confusion Matrix - CatBoost")
plt.show()

from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    objective="multi:softprob",
    num_class=3,
    random_state=42,
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8
)

xgb_model.fit(X_train_smote, y_train_smote)
y_pred_xgb = xgb_model.predict(X_test)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# confusion matrix
cm = confusion_matrix(y_test, y_pred_xgb)

# label (sesuaikan dengan encoding kamu)
labels = ["Moderate", "Normal", "Severe"]

plt.figure()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels,
            yticklabels=labels)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - XGBoost")
plt.show()
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', linewidths=1)

from catboost import CatBoostClassifier

cat_model = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.1,
    loss_function='MultiClass',
    random_state=42,
    verbose=0
)

cat_model.fit(X_train_smote, y_train_smote)
y_pred_cat = cat_model.predict(X_test)
y_pred_cat = y_pred_cat.flatten().astype(int)

# =========================
# SVM
# =========================
from sklearn.svm import SVC
svm_model = SVC(kernel="rbf", random_state=42)
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

# =========================
# KNN
# =========================
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)

# =========================
# Naive Bayes
# =========================
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred_nb = nb_model.predict(X_test)

# =========================
# Decision Tree
# =========================
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

from sklearn.metrics import accuracy_score, f1_score, recall_score
import pandas as pd

results = []

# =========================
# Logistic Regression
# =========================
results.append({
    "model": "Logistic Regression",
    "accuracy": accuracy_score(y_test, y_pred_log),
    "f1": f1_score(y_test, y_pred_log, average='weighted'),
    "recall": recall_score(y_test, y_pred_log, average='weighted')
})

# =========================
# Random Forest
# =========================
results.append({
    "model": "Random Forest",
    "accuracy": accuracy_score(y_test, y_pred_rf),
    "f1": f1_score(y_test, y_pred_rf, average='weighted'),
    "recall": recall_score(y_test, y_pred_rf, average='weighted')
})

# =========================
# XGBoost
# =========================
results.append({
    "model": "XGBoost",
    "accuracy": accuracy_score(y_test, y_pred_xgb),
    "f1": f1_score(y_test, y_pred_xgb, average='weighted'),
    "recall": recall_score(y_test, y_pred_xgb, average='weighted')
})

# =========================
# CatBoost
# =========================
results.append({
    "model": "CatBoost",
    "accuracy": accuracy_score(y_test, y_pred_cat),
    "f1": f1_score(y_test, y_pred_cat, average='weighted'),
    "recall": recall_score(y_test, y_pred_cat, average='weighted')
})

# =========================
# Support Vector Machine (SVM)
# =========================
results.append({
    "model": "SVM",
    "accuracy": accuracy_score(y_test, y_pred_svm),
    "f1": f1_score(y_test, y_pred_svm, average='weighted'),
    "recall": recall_score(y_test, y_pred_svm, average='weighted')
})

# =========================
# K-Nearest Neighbors (KNN)
# =========================
results.append({
    "model": "KNN",
    "accuracy": accuracy_score(y_test, y_pred_knn),
    "f1": f1_score(y_test, y_pred_knn, average='weighted'),
    "recall": recall_score(y_test, y_pred_knn, average='weighted')
})

# =========================
# Naive Bayes
# =========================
results.append({
    "model": "Naive Bayes",
    "accuracy": accuracy_score(y_test, y_pred_nb),
    "f1": f1_score(y_test, y_pred_nb, average='weighted'),
    "recall": recall_score(y_test, y_pred_nb, average='weighted')
})

# =========================
# Decision Tree
# =========================
results.append({
    "model": "Decision Tree",
    "accuracy": accuracy_score(y_test, y_pred_dt),
    "f1": f1_score(y_test, y_pred_dt, average='weighted'),
    "recall": recall_score(y_test, y_pred_dt, average='weighted')
})

# =========================
# RESULT TABLE
# =========================
df_results = pd.DataFrame(results)

# sort by recall (important for medical case)
df_results = df_results.sort_values(by="recall", ascending=False)

print(df_results)

# Best model
print("\nBest Model:", df_results.iloc[0]["model"])

import pandas as pd

results_df = pd.DataFrame(results)
print(results_df)

best_model_row = results_df.loc[results_df['f1'].idxmax()]

print("\n=== FINAL BEST MODEL ===")
print(best_model_row)

new_data = pd.DataFrame([
    {
    "age_months": 24,
    "weight_kg": 6.0,
    "height_cm": 72,
    "muac_cm": 11.0,
    "bmi": 11.5
    }
])

new_data = new_data[numeric_cols]

# Assign the best model based on previous analysis
if best_model_row['model'] == "XGBoost":
    final_model = xgb_model
elif best_model_row['model'] == "Random Forest":
    final_model = best_rf
elif best_model_row['model'] == "Logistic Regression":
    final_model = best_log
elif best_model_row['model'] == "CatBoost":
    final_model = cat_model

# Handle scaling for Logistic Regression if it's the best model
if best_model_row['model'] == "Logistic Regression":
    new_data_processed = scaler.transform(new_data)
else:
    new_data_processed = new_data

pred = final_model.predict(new_data_processed)

# specific handling for CatBoost output format
if best_model_row['model'] == "CatBoost":
    pred = pred.flatten().astype(int)

result = label_encoder.inverse_transform(pred)

print("Final Prediction:", result[0])

import pandas as pd

new_data = pd.DataFrame([{
    "age_months": 24,
    "weight_kg": 9.0,
    "height_cm": 80,
    "muac_cm": 13.8,
    "bmi": 14.0
}])

new_data = new_data[numeric_cols]

pred = xgb_model.predict(new_data)
result = label_encoder.inverse_transform(pred)

proba = xgb_model.predict_proba(new_data)

print("Predicted:", result[0])
for cls, p in zip(label_encoder.classes_, proba[0]):
    print(f"{cls}: {p:.2%}")

new_data = pd.DataFrame([{
    "age_months": 24,
    "weight_kg": 6.5,
    "height_cm": 73,
    "muac_cm": 11.5,
    "bmi": 12.0
}])

new_data = new_data[numeric_cols]

pred = xgb_model.predict(new_data)
result = label_encoder.inverse_transform(pred)

proba = xgb_model.predict_proba(new_data)

print("Predicted:", result[0])
for cls, p in zip(label_encoder.classes_, proba[0]):
    print(f"{cls}: {p:.2%}")

new_data = pd.DataFrame([{
    "age_months": 24,
    "weight_kg": 3.0,
    "height_cm": 60,
    "muac_cm": 10.0,
    "bmi": 8.3
}])

new_data = new_data[numeric_cols]

pred = xgb_model.predict(new_data)
result = label_encoder.inverse_transform(pred)

proba = xgb_model.predict_proba(new_data)

print("Predicted:", result[0])
for cls, p in zip(label_encoder.classes_, proba[0]):
    print(f"{cls}: {p:.2%}")

import joblib

joblib.dump(xgb_model, "xgboost_model.pkl")

import pandas as pd
import matplotlib.pyplot as plt

# Data hasil evaluasi model
model_results = {
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost",
        "CatBoost",
        "KNN",
        "SVM",
        "Decision Tree",
        "Naive Bayes"
    ],
    "Accuracy": [0.935, 0.953, 0.959, 0.951, 0.946, 0.869, 0.921, 0.675],
    "F1-Score": [0.936, 0.953, 0.959, 0.952, 0.945, 0.852, 0.921, 0.705],
    "Recall": [0.935, 0.953, 0.959, 0.951, 0.946, 0.869, 0.921, 0.675]
}

df_results = pd.DataFrame(model_results)

# Ubah ke persen
df_plot = df_results.copy()
df_plot[["Accuracy", "F1-Score", "Recall"]] *= 100

# Grafik Accuracy
plt.figure(figsize=(10, 6))
plt.bar(df_plot["Model"], df_plot["Accuracy"])
plt.xticks(rotation=45, ha="right")
plt.ylabel("Accuracy (%)")
plt.title("Model Accuracy Comparison")
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Data recall semua model
model_results = {
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost",
        "CatBoost",
        "KNN",
        "SVM",
        "Decision Tree",
        "Naive Bayes"
    ],
    "Recall": [
        0.935,
        0.953,
        0.959,
        0.951,
        0.946,
        0.869,
        0.921,
        0.675
    ]
}

df_recall = pd.DataFrame(model_results)

# Ubah ke persen
df_recall["Recall (%)"] = df_recall["Recall"] * 100

# Urutkan dari terbesar
df_recall = df_recall.sort_values("Recall (%)", ascending=False)

plt.figure(figsize=(10, 6))
plt.bar(df_recall["Model"], df_recall["Recall (%)"])

plt.title("Recall Comparison of Machine Learning Models")
plt.xlabel("Models")
plt.ylabel("Recall (%)")
plt.ylim(60, 100)
plt.xticks(rotation=45, ha="right")

# tampilkan angka di atas bar
for i, v in enumerate(df_recall["Recall (%)"]):
    plt.text(i, v + 0.5, f"{v:.1f}%", ha="center")

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

models = [
    "Logistic Regression", "Random Forest", "XGBoost",
    "CatBoost", "KNN", "SVM", "Decision Tree", "Naive Bayes"
]

precision = [0.936, 0.953, 0.959, 0.952, 0.945, 0.852, 0.921, 0.705]

df = pd.DataFrame({"Model": models, "Precision": precision})
df["Precision (%)"] = df["Precision"] * 100
df = df.sort_values("Precision (%)", ascending=False)

plt.figure(figsize=(10,6))
plt.bar(df["Model"], df["Precision (%)"])

plt.title("Precision Comparison")
plt.ylabel("Precision (%)")
plt.xticks(rotation=45, ha="right")

for i, v in enumerate(df["Precision (%)"]):
    plt.text(i, v+0.5, f"{v:.1f}%", ha="center")

plt.tight_layout()
plt.show()

f1 = [0.936, 0.953, 0.959, 0.952, 0.945, 0.852, 0.921, 0.705]

df = pd.DataFrame({"Model": models, "F1": f1})
df["F1 (%)"] = df["F1"] * 100
df = df.sort_values("F1 (%)", ascending=False)

plt.figure(figsize=(10,6))
plt.bar(df["Model"], df["F1 (%)"])

plt.title("F1-Score Comparison")
plt.ylabel("F1 Score (%)")
plt.xticks(rotation=45, ha="right")

for i, v in enumerate(df["F1 (%)"]):
    plt.text(i, v+0.5, f"{v:.1f}%", ha="center")

plt.tight_layout()
plt.show()

joblib.dump(xgb_model, "xgboost_model.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")
